spring.application.name=LetraVia
server.port=8090


spring.datasource.url=jdbc:postgresql://dpg-d6ae0uvgi27c73b61lh0-a.oregon-postgres.render.com:5432/analfabetismo
spring.datasource.username=analfabetismo_user
spring.datasource.password=ED9SEaqIbEK8YTqDpXNTCQkfAAzlFb1Y

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.sersialization.indent-output=true
spring.jpa.properties.hibernate.format_sql=true