spring.application.name=LetraVia
server.port=8090


spring.datasource.url=jdbc:mysql://localhost:3306/analfabetismo_in5am?createDatabaseIfNotExist=true
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.serialization.indent-output=true
spring.jpa.properties.hibernate.format_sql=true